/**
 * Client-side ATS keyword optimization helpers — mirrors
 * `supabase/functions/_shared/ats_keyword_optimization.ts`.
 */

export {
  ATS_MAX_TEXT_MODIFICATION_RATIO,
  ATS_OPTIMIZATION_POLICY,
  ATS_OPTIMIZE_CONFIRM_EXAMPLES,
  ATS_NO_KEYWORDS_MESSAGE,
  ATS_PREVIEW_KEYWORD_CHANGE_COUNT,
  DISCOVERY_MAX_VISUAL_WIDTH_DELTA_RATIO,
  EXPORT_MAX_VISUAL_WIDTH_DELTA_RATIO,
  MAX_VISUAL_WIDTH_DELTA_RATIO,
  REVIEW_MAX_VISUAL_WIDTH_DELTA_RATIO,
  applyKeywordChangeAtOccurrence,
  buildAtsOptimizationScanResult,
  buildOptimizedResumeText,
  buildPhraseBoundaryPattern,
  classifyAtsSafetyScore,
  computeLayoutPreservationScore,
  computeOptimizedAtsScore,
  computeTypographyPreservationScore,
  computeVisualWidthDeltaPercent,
  createEmptyRejectionCounts,
  detectAbnormalWhitespace,
  evaluateLayoutPreservation,
  evaluateTypographyPreservation,
  formatAtsSafetyScoreLabel,
  getContextAwareReplacements,
  isBulletLine,
  isScannableAccomplishmentLine,
  KEYWORD_REPLACEMENT_POOL,
  logKeywordDiscoveryStats,
  occurrenceIndexForChange,
  passesStageWidthTolerance,
  passesVisualWidthTolerance,
  PRODUCT_DESIGN_REPLACEMENT_POOL,
  scanResumeForKeywordChanges,
  scanResumeWithDiscovery,
  validateReplacementIntegrity,
  validateResumeStructurePreserved,
  visualWidthDeltaPercentForChange,
  WEAK_VERB_REPLACEMENT_POOL,
  withVisualWidthDelta,
} from "./ats-keyword-optimization-shared";

export type {
  AtsKeywordDiagnostics,
  AtsSafetyScore,
  KeywordDiscoveryResult,
  KeywordRejectionCounts,
  KeywordRejectionReason,
  LayoutPreservationMetadata,
  RejectedKeywordCandidate,
  ValidationStage,
} from "./ats-keyword-optimization-shared";
